"""Updated models

Revision ID: 455152df0da4
Revises: 
Create Date: 2025-01-01 18:37:34.665584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455152df0da4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appliance_insights')
    op.drop_table('maintenance_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appliance_insights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('appliance_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('energy_usage', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('estimated_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('usage_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
