"""Updated outages

Revision ID: 9a46b0d61b64
Revises: 455152df0da4
Create Date: 2025-01-02 12:41:39.616166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a46b0d61b64'
down_revision = '455152df0da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heatmapdata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outages', schema=None) as batch_op:
        batch_op.drop_column('heatmapdata')

    # ### end Alembic commands ###
